#define EX_MOUSE 1
#define EX_KEY 2
#define EX_CHAR 4
#define EX_WINDOW 8

#define BACK_WIDTH 481
#define BACK_HEIGHT 268

#define BACK_MOVE_STEP 3
#define BACK_MOVE_TIMERID 1
#define BACK_MOVE_INTERVAL 50

#define PLAYER_MOVE_TIMERID 3
#define PLAYER_MOVE_INTERVAL 50

#define CHANGE_PIC_TIMERID 4 
#define CHANGE_PIC_INTERVAL 100

#define OBST_CREATE_TIMERID 5
#define OBST_CREATE_INTERVAL 700

#define OBS_MOVE_TIMERID 6
#define OBS_MOVE_INTERVAL 50

#define DELETE_OBS_TIMERID 7
#define DELETE_OBS_INTERVAL 1000//定时回收障碍物

#define OBSF_CREATE_TIMERID 8
#define OBSF_CREATE_INTERVAL 4000

#define CHECK_BOOM_TIMERID 9
#define CHECK_BOOM_INTERVAL 30

#define SCORE_TIMERID 10
#define SCORE_INTERVAL 1000

#define PLAYER_INIT_X 60
#define PLAYER_INIT_Y 80
#define PLAYER_WIDTH 67
#define PLAYER_HEIGHT 39
#define PLAYER_UP_MOVE_STEP 14
#define PLAYER_DOWN_MOVE_STEP 2


#define OBS_MOVE_STEP 3
#define OBS_WIDTH 32
#define OBS_HEIGHT 64
